#!/bin/bash
# Generated file. Do not modify by hand.
# Usage: script <CARCH>
place_subproject_into_tree () {
    # place_subproject_into_tree flattened_path path
    local parent_dir="$(dirname "$2")"
    if [[ -n "$parent_dir" ]]; then
        mkdir -p "$parent_dir"
    fi
    # Remove the target dir only if it's empty
    rm -df "$2"
    mv -v "$1" "$2"
}

CARCH="$1"
case "$CARCH" in
    x86_64)
        _go_arch=amd64;;
    *)
        _go_arch="$CARCH";;
esac

place_subproject_into_tree chromium-mirror src
place_subproject_into_tree chromium-mirror_third_party_nan src/third_party/nan
place_subproject_into_tree chromium-mirror_third_party_electron_node src/third_party/electron_node
place_subproject_into_tree chromium-mirror_third_party_engflow-reclient-configs src/third_party/engflow-reclient-configs
place_subproject_into_tree chromium-mirror_third_party_clang-format_script src/third_party/clang-format/script
place_subproject_into_tree chromium-mirror_third_party_libc++_src src/third_party/libc++/src
place_subproject_into_tree chromium-mirror_third_party_libc++abi_src src/third_party/libc++abi/src
place_subproject_into_tree chromium-mirror_third_party_libunwind_src src/third_party/libunwind/src
place_subproject_into_tree chromium-mirror_chrome_test_data_perf_canvas_bench src/chrome/test/data/perf/canvas_bench
place_subproject_into_tree chromium-mirror_chrome_test_data_perf_frame_rate_content src/chrome/test/data/perf/frame_rate/content
place_subproject_into_tree chromium-mirror_chrome_test_data_xr_webvr_info src/chrome/test/data/xr/webvr_info
place_subproject_into_tree chromium-mirror_media_cdm_api src/media/cdm/api
place_subproject_into_tree chromium-mirror_native_client src/native_client
place_subproject_into_tree chromium-mirror_net_third_party_quiche_src src/net/third_party/quiche/src
place_subproject_into_tree chromium-mirror_third_party_angle src/third_party/angle
place_subproject_into_tree chromium-mirror_third_party_anonymous_tokens_src src/third_party/anonymous_tokens/src
place_subproject_into_tree chromium-mirror_third_party_content_analysis_sdk_src src/third_party/content_analysis_sdk/src
place_subproject_into_tree chromium-mirror_third_party_dav1d_libdav1d src/third_party/dav1d/libdav1d
place_subproject_into_tree chromium-mirror_third_party_dawn src/third_party/dawn
place_subproject_into_tree chromium-mirror_third_party_highway_src src/third_party/highway/src
place_subproject_into_tree chromium-mirror_third_party_google_benchmark_src src/third_party/google_benchmark/src
place_subproject_into_tree chromium-mirror_third_party_boringssl_src src/third_party/boringssl/src
place_subproject_into_tree chromium-mirror_third_party_breakpad_breakpad src/third_party/breakpad/breakpad
place_subproject_into_tree chromium-mirror_third_party_cast_core_public_src src/third_party/cast_core/public/src
place_subproject_into_tree chromium-mirror_third_party_catapult src/third_party/catapult
place_subproject_into_tree chromium-mirror_third_party_ced_src src/third_party/ced/src
place_subproject_into_tree chromium-mirror_third_party_chromium-variations src/third_party/chromium-variations
place_subproject_into_tree chromium-mirror_third_party_cld_3_src src/third_party/cld_3/src
place_subproject_into_tree chromium-mirror_third_party_colorama_src src/third_party/colorama/src
place_subproject_into_tree chromium-mirror_third_party_cpu_features_src src/third_party/cpu_features/src
place_subproject_into_tree chromium-mirror_third_party_cpuinfo_src src/third_party/cpuinfo/src
place_subproject_into_tree chromium-mirror_third_party_crc32c_src src/third_party/crc32c/src
place_subproject_into_tree chromium-mirror_third_party_cros_system_api src/third_party/cros_system_api
place_subproject_into_tree chromium-mirror_third_party_crossbench src/third_party/crossbench
place_subproject_into_tree chromium-mirror_third_party_depot_tools src/third_party/depot_tools
place_subproject_into_tree chromium-mirror_third_party_devtools-frontend_src src/third_party/devtools-frontend/src
place_subproject_into_tree chromium-mirror_third_party_dom_distiller_js_dist src/third_party/dom_distiller_js/dist
place_subproject_into_tree chromium-mirror_third_party_eigen3_src src/third_party/eigen3/src
place_subproject_into_tree chromium-mirror_third_party_farmhash_src src/third_party/farmhash/src
place_subproject_into_tree chromium-mirror_third_party_ffmpeg src/third_party/ffmpeg
place_subproject_into_tree chromium-mirror_third_party_flac src/third_party/flac
place_subproject_into_tree chromium-mirror_third_party_flatbuffers_src src/third_party/flatbuffers/src
place_subproject_into_tree chromium-mirror_third_party_fontconfig_src src/third_party/fontconfig/src
place_subproject_into_tree chromium-mirror_third_party_fp16_src src/third_party/fp16/src
place_subproject_into_tree chromium-mirror_third_party_gemmlowp_src src/third_party/gemmlowp/src
place_subproject_into_tree chromium-mirror_third_party_grpc_src src/third_party/grpc/src
place_subproject_into_tree chromium-mirror_third_party_freetype_src src/third_party/freetype/src
place_subproject_into_tree chromium-mirror_third_party_freetype-testing_src src/third_party/freetype-testing/src
place_subproject_into_tree chromium-mirror_third_party_fxdiv_src src/third_party/fxdiv/src
place_subproject_into_tree chromium-mirror_third_party_harfbuzz-ng_src src/third_party/harfbuzz-ng/src
place_subproject_into_tree chromium-mirror_third_party_emoji-segmenter_src src/third_party/emoji-segmenter/src
place_subproject_into_tree chromium-mirror_third_party_ots_src src/third_party/ots/src
place_subproject_into_tree chromium-mirror_third_party_libgav1_src src/third_party/libgav1/src
place_subproject_into_tree chromium-mirror_third_party_googletest_src src/third_party/googletest/src
place_subproject_into_tree chromium-mirror_third_party_hunspell_dictionaries src/third_party/hunspell_dictionaries
place_subproject_into_tree chromium-mirror_third_party_icu src/third_party/icu
place_subproject_into_tree chromium-mirror_third_party_jsoncpp_source src/third_party/jsoncpp/source
place_subproject_into_tree chromium-mirror_third_party_leveldatabase_src src/third_party/leveldatabase/src
place_subproject_into_tree chromium-mirror_third_party_libFuzzer_src src/third_party/libFuzzer/src
place_subproject_into_tree chromium-mirror_third_party_fuzztest_src src/third_party/fuzztest/src
place_subproject_into_tree chromium-mirror_third_party_libaddressinput_src src/third_party/libaddressinput/src
place_subproject_into_tree chromium-mirror_third_party_libaom_source_libaom src/third_party/libaom/source/libaom
place_subproject_into_tree chromium-mirror_third_party_libavif_src src/third_party/libavif/src
place_subproject_into_tree chromium-mirror_third_party_libavifinfo_src src/third_party/libavifinfo/src
place_subproject_into_tree chromium-mirror_third_party_nearby_src src/third_party/nearby/src
place_subproject_into_tree chromium-mirror_third_party_beto-core_src src/third_party/beto-core/src
place_subproject_into_tree chromium-mirror_third_party_securemessage_src src/third_party/securemessage/src
place_subproject_into_tree chromium-mirror_third_party_speedometer_v3.0 src/third_party/speedometer/v3.0
place_subproject_into_tree chromium-mirror_third_party_ukey2_src src/third_party/ukey2/src
place_subproject_into_tree chromium-mirror_third_party_cros-components_src src/third_party/cros-components/src
place_subproject_into_tree chromium-mirror_third_party_libdrm_src src/third_party/libdrm/src
place_subproject_into_tree chromium-mirror_third_party_expat_src src/third_party/expat/src
place_subproject_into_tree chromium-mirror_third_party_libipp_libipp src/third_party/libipp/libipp
place_subproject_into_tree chromium-mirror_third_party_libjpeg_turbo src/third_party/libjpeg_turbo
place_subproject_into_tree chromium-mirror_third_party_liblouis_src src/third_party/liblouis/src
place_subproject_into_tree chromium-mirror_third_party_libphonenumber_dist src/third_party/libphonenumber/dist
place_subproject_into_tree chromium-mirror_third_party_libprotobuf-mutator_src src/third_party/libprotobuf-mutator/src
place_subproject_into_tree chromium-mirror_third_party_libsrtp src/third_party/libsrtp
place_subproject_into_tree chromium-mirror_third_party_libsync_src src/third_party/libsync/src
place_subproject_into_tree chromium-mirror_third_party_libvpx_source_libvpx src/third_party/libvpx/source/libvpx
place_subproject_into_tree chromium-mirror_third_party_libwebm_source src/third_party/libwebm/source
place_subproject_into_tree chromium-mirror_third_party_libwebp_src src/third_party/libwebp/src
place_subproject_into_tree chromium-mirror_third_party_libyuv src/third_party/libyuv
place_subproject_into_tree chromium-mirror_third_party_lss src/third_party/lss
place_subproject_into_tree chromium-mirror_third_party_material_color_utilities_src src/third_party/material_color_utilities/src
place_subproject_into_tree chromium-mirror_third_party_minigbm_src src/third_party/minigbm/src
place_subproject_into_tree chromium-mirror_third_party_nasm src/third_party/nasm
place_subproject_into_tree chromium-mirror_third_party_neon_2_sse_src src/third_party/neon_2_sse/src
place_subproject_into_tree chromium-mirror_third_party_openh264_src src/third_party/openh264/src
place_subproject_into_tree chromium-mirror_third_party_openscreen_src src/third_party/openscreen/src
place_subproject_into_tree chromium-mirror_third_party_openxr_src src/third_party/openxr/src
place_subproject_into_tree chromium-mirror_third_party_pdfium src/third_party/pdfium
place_subproject_into_tree chromium-mirror_third_party_perfetto src/third_party/perfetto
place_subproject_into_tree chromium-mirror_third_party_pthreadpool_src src/third_party/pthreadpool/src
place_subproject_into_tree chromium-mirror_third_party_pyelftools src/third_party/pyelftools
place_subproject_into_tree chromium-mirror_third_party_quic_trace_src src/third_party/quic_trace/src
place_subproject_into_tree chromium-mirror_third_party_pywebsocket3_src src/third_party/pywebsocket3/src
place_subproject_into_tree chromium-mirror_third_party_re2_src src/third_party/re2/src
place_subproject_into_tree chromium-mirror_third_party_ruy_src src/third_party/ruy/src
place_subproject_into_tree chromium-mirror_third_party_skia src/third_party/skia
place_subproject_into_tree chromium-mirror_third_party_smhasher_src src/third_party/smhasher/src
place_subproject_into_tree chromium-mirror_third_party_snappy_src src/third_party/snappy/src
place_subproject_into_tree chromium-mirror_third_party_sqlite_src src/third_party/sqlite/src
place_subproject_into_tree chromium-mirror_third_party_swiftshader src/third_party/swiftshader
place_subproject_into_tree chromium-mirror_third_party_text-fragments-polyfill_src src/third_party/text-fragments-polyfill/src
place_subproject_into_tree chromium-mirror_third_party_tflite_src src/third_party/tflite/src
place_subproject_into_tree chromium-mirror_third_party_vulkan-deps src/third_party/vulkan-deps
place_subproject_into_tree chromium-mirror_third_party_vulkan_memory_allocator src/third_party/vulkan_memory_allocator
place_subproject_into_tree chromium-mirror_third_party_wayland_src src/third_party/wayland/src
place_subproject_into_tree chromium-mirror_third_party_wayland-protocols_src src/third_party/wayland-protocols/src
place_subproject_into_tree chromium-mirror_third_party_wayland-protocols_kde src/third_party/wayland-protocols/kde
place_subproject_into_tree chromium-mirror_third_party_wayland-protocols_gtk src/third_party/wayland-protocols/gtk
place_subproject_into_tree chromium-mirror_third_party_webdriver_pylib src/third_party/webdriver/pylib
place_subproject_into_tree chromium-mirror_third_party_webgl_src src/third_party/webgl/src
place_subproject_into_tree chromium-mirror_third_party_webgpu-cts_src src/third_party/webgpu-cts/src
place_subproject_into_tree chromium-mirror_third_party_webrtc src/third_party/webrtc
place_subproject_into_tree chromium-mirror_third_party_wuffs_src src/third_party/wuffs/src
place_subproject_into_tree chromium-mirror_third_party_weston_src src/third_party/weston/src
place_subproject_into_tree chromium-mirror_third_party_xdg-utils src/third_party/xdg-utils
place_subproject_into_tree chromium-mirror_third_party_xnnpack_src src/third_party/xnnpack/src
place_subproject_into_tree chromium-mirror_tools_page_cycler_acid3 src/tools/page_cycler/acid3
place_subproject_into_tree chromium-mirror_third_party_zstd_src src/third_party/zstd/src
place_subproject_into_tree chromium-mirror_v8 src/v8
place_subproject_into_tree chromium-mirror_third_party_angle_third_party_glmark2_src src/third_party/angle/third_party/glmark2/src
place_subproject_into_tree chromium-mirror_third_party_angle_third_party_rapidjson_src src/third_party/angle/third_party/rapidjson/src
place_subproject_into_tree chromium-mirror_third_party_angle_third_party_VK-GL-CTS_src src/third_party/angle/third_party/VK-GL-CTS/src
place_subproject_into_tree chromium-mirror_third_party_dawn_buildtools src/third_party/dawn/buildtools
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_clang-format_script src/third_party/dawn/third_party/clang-format/script
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_libc++_src src/third_party/dawn/third_party/libc++/src
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_libc++abi_src src/third_party/dawn/third_party/libc++abi/src
place_subproject_into_tree chromium-mirror_third_party_dawn_build src/third_party/dawn/build
place_subproject_into_tree chromium-mirror_third_party_dawn_tools_clang src/third_party/dawn/tools/clang
place_subproject_into_tree chromium-mirror_third_party_dawn_testing src/third_party/dawn/testing
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_libFuzzer_src src/third_party/dawn/third_party/libFuzzer/src
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_googletest src/third_party/dawn/third_party/googletest
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_catapult src/third_party/dawn/third_party/catapult
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_google_benchmark_src src/third_party/dawn/third_party/google_benchmark/src
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_jinja2 src/third_party/dawn/third_party/jinja2
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_markupsafe src/third_party/dawn/third_party/markupsafe
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_glfw src/third_party/dawn/third_party/glfw
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_vulkan_memory_allocator src/third_party/dawn/third_party/vulkan_memory_allocator
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_angle src/third_party/dawn/third_party/angle
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_swiftshader src/third_party/dawn/third_party/swiftshader
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_vulkan-deps src/third_party/dawn/third_party/vulkan-deps
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_zlib src/third_party/dawn/third_party/zlib
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_abseil-cpp src/third_party/dawn/third_party/abseil-cpp
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_dxc src/third_party/dawn/third_party/dxc
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_dxheaders src/third_party/dawn/third_party/dxheaders
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_khronos_OpenGL-Registry src/third_party/dawn/third_party/khronos/OpenGL-Registry
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_khronos_EGL-Registry src/third_party/dawn/third_party/khronos/EGL-Registry
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_webgpu-cts src/third_party/dawn/third_party/webgpu-cts
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_protobuf src/third_party/dawn/third_party/protobuf
place_subproject_into_tree chromium-mirror_third_party_dawn_tools_protoc_wrapper src/third_party/dawn/tools/protoc_wrapper
place_subproject_into_tree chromium-mirror_third_party_dawn_third_party_partition_alloc src/third_party/dawn/third_party/partition_alloc
place_subproject_into_tree chromium-mirror_third_party_openscreen_src_buildtools src/third_party/openscreen/src/buildtools
place_subproject_into_tree chromium-mirror_third_party_openscreen_src_third_party_tinycbor_src src/third_party/openscreen/src/third_party/tinycbor/src
place_subproject_into_tree chromium-mirror_third_party_vulkan-deps_glslang_src src/third_party/vulkan-deps/glslang/src
place_subproject_into_tree chromium-mirror_third_party_vulkan-deps_spirv-cross_src src/third_party/vulkan-deps/spirv-cross/src
place_subproject_into_tree chromium-mirror_third_party_vulkan-deps_spirv-headers_src src/third_party/vulkan-deps/spirv-headers/src
place_subproject_into_tree chromium-mirror_third_party_vulkan-deps_spirv-tools_src src/third_party/vulkan-deps/spirv-tools/src
place_subproject_into_tree chromium-mirror_third_party_vulkan-deps_vulkan-headers_src src/third_party/vulkan-deps/vulkan-headers/src
place_subproject_into_tree chromium-mirror_third_party_vulkan-deps_vulkan-loader_src src/third_party/vulkan-deps/vulkan-loader/src
place_subproject_into_tree chromium-mirror_third_party_vulkan-deps_vulkan-tools_src src/third_party/vulkan-deps/vulkan-tools/src
place_subproject_into_tree chromium-mirror_third_party_vulkan-deps_vulkan-utility-libraries_src src/third_party/vulkan-deps/vulkan-utility-libraries/src
place_subproject_into_tree chromium-mirror_third_party_vulkan-deps_vulkan-validation-layers_src src/third_party/vulkan-deps/vulkan-validation-layers/src
cp electron29-gclient_args.gni src/build/config/gclient_args.gni
cipd install chromium/third_party/screen-ai/linux x8c4xOQj3V2uyBicjNa2YkN71brkj5FZg157RueHF_oC -root src/third_party/screen-ai/linux
cipd install infra/3pp/tools/esbuild/linux-${_go_arch} version:2@0.14.13.chromium.2 -root src/third_party/devtools-frontend/src/third_party/esbuild